use demo;
create table department(department_id int not null AUTO_INCREMENT, department_name varchar(25), primary key(department_id));
create table floors(floor_id int not null AUTO_INCREMENT, floor_name varchar(20), department_id int,primary key(floor_id), FOREIGN KEY(department_id) REFERENCES department(department_id));
create table employee(employee_id int not null AUTO_INCREMENT, employee_name varchar(50) not null,isActive boolean,employee_department int,primary key(employee_id), FOREIGN KEY(employee_department) REFERENCES department(department_id));
create table cubicle(cubicle_id int NOT NULL AUTO_INCREMENT,cubicle_number varchar(10), floor_id int, isVacant boolean, allocated_to int,primary key(cubicle_id),FOREIGN KEY(allocated_to) REFERENCES employee(employee_id), FOREIGN KEY(floor_id) REFERENCES floors(floor_id));
select * from department;
insert into department(department_name) values ("Platform");
insert into department(department_name) values ("Management");
insert into department(department_name) values ("Cutomer360");
insert into department(department_name) values ("TargetOne");
insert into department(department_name) values ("ProfessionalServices");
insert into department(department_name) values ("Maya");
insert into department(department_name) values ("Finance");
insert into department(department_name) values ("DataScience");
insert into department(department_name) values ("UI");
insert into department(department_name) values ("Database");
insert into department(department_name) values ("Sales");
insert into department(department_name) values ("HR");
insert into department(department_name) values ("Marketing");
insert into department(department_name) values ("Operations");
insert into department(department_name) values ("IT");
insert into department(department_name) values ("QA");
insert into department(department_name) values ("Cloud");
select * from floors;
insert into floors(floor_name,department_id) values("FirstFloor",1);
insert into floors(floor_name,department_id) values("FirstFloor",2);
insert into floors(floor_name,department_id) values("ThirdFloor",3);
insert into floors(floor_name,department_id) values("ThirdFloor",4);
insert into floors(floor_name,department_id) values("FourthFloor",5);
insert into floors(floor_name,department_id) values("FirstFloor",6);
insert into floors(floor_name,department_id) values("FirstFloor",7);
insert into floors(floor_name,department_id) values("FirstFloor",8);
insert into floors(floor_name,department_id) values("FirstFloor",9);
insert into floors(floor_name,department_id) values("ThirdFloor",10);
insert into floors(floor_name,department_id) values("FourthFloor",11);
insert into floors(floor_name,department_id) values("SecondFloor",12);
insert into floors(floor_name,department_id) values("FirstFloor",13);
insert into floors(floor_name,department_id) values("SecondFloor",14);
insert into floors(floor_name,department_id) values("FirstFloor",15);
insert into floors(floor_name,department_id) values("ThirdFloor",16);
insert into floors(floor_name,department_id) values("FourthFloor",17);
select * from employee;
insert into employee(employee_name,isActive,employee_department) values("Abhi",true,1);
insert into employee(employee_name,isActive,employee_department) values("Akash",true,2);
insert into employee(employee_name,isActive,employee_department) values("Ben",true,3);
insert into employee(employee_name,isActive,employee_department) values("Charan",true,4);
insert into employee(employee_name,isActive,employee_department) values("David",true,5);
insert into employee(employee_name,isActive,employee_department) values("Goutham",true,6);
insert into employee(employee_name,isActive,employee_department) values("Harsh",true,7);
insert into employee(employee_name,isActive,employee_department) values("Karan",true,8);
insert into employee(employee_name,isActive,employee_department) values("Lucky",true,9);
insert into employee(employee_name,isActive,employee_department) values("Manu",true,10);
insert into employee(employee_name,isActive,employee_department) values("Yuvi",true,11);
insert into employee(employee_name,isActive,employee_department) values("Mahesh",true,12);
insert into employee(employee_name,isActive,employee_department) values("Suresh",true,13);
insert into employee(employee_name,isActive,employee_department) values("Ramesh",true,14);
insert into employee(employee_name,isActive,employee_department) values("Ram",true,15);
insert into employee(employee_name,isActive,employee_department) values("Sham",true,16);
insert into employee(employee_name,isActive,employee_department) values("Chenu",true,17);
select * from cubicle;

insert into cubicle(cubicle_number,floor_id,isVacant,allocated_to) values("1F001",1,false,1);
insert into cubicle(cubicle_number,floor_id,isVacant,allocated_to) values("1F002",2,false,2);
insert into cubicle(cubicle_number,floor_id,isVacant,allocated_to) values("1F003",6,false,6);
insert into cubicle(cubicle_number,floor_id,isVacant,allocated_to) values("1F004",7,false,7);
insert into cubicle(cubicle_number,floor_id,isVacant,allocated_to) values("1F005",8,false,8);
insert into cubicle(cubicle_number,floor_id,isVacant,allocated_to) values("1F006",9,false,9);
insert into cubicle(cubicle_number,floor_id,isVacant,allocated_to) values("1F007",13,false,13);
insert into cubicle(cubicle_number,floor_id,isVacant,allocated_to) values("1F008",15,false,15);
insert into cubicle(cubicle_number,isVacant) values("1F009",true);
insert into cubicle(cubicle_number,isVacant) values("1F010",true);

insert into cubicle(cubicle_number,floor_id,isVacant,allocated_to) values("2F001",12,false,12);
insert into cubicle(cubicle_number,floor_id,isVacant,allocated_to) values("2F002",14,false,14);
insert into cubicle(cubicle_number,isVacant) values("2F003",true);
insert into cubicle(cubicle_number,isVacant) values("2F004",true);
insert into cubicle(cubicle_number,isVacant) values("2F005",true);
insert into cubicle(cubicle_number,isVacant) values("2F006",true);
insert into cubicle(cubicle_number,isVacant) values("2F007",true);
insert into cubicle(cubicle_number,isVacant) values("2F008",true);
insert into cubicle(cubicle_number,isVacant) values("2F009",true);
insert into cubicle(cubicle_number,isVacant) values("2F010",true);

insert into cubicle(cubicle_number,floor_id,isVacant,allocated_to) values("3F001",3,false,3);
insert into cubicle(cubicle_number,floor_id,isVacant,allocated_to) values("3F002",4,false,3);
insert into cubicle(cubicle_number,floor_id,isVacant,allocated_to) values("3F003",10,false,10);
insert into cubicle(cubicle_number,floor_id,isVacant,allocated_to) values("3F004",16,false,16);
insert into cubicle(cubicle_number,isVacant) values("2F005",true);
insert into cubicle(cubicle_number,isVacant) values("2F006",true);
insert into cubicle(cubicle_number,isVacant) values("2F007",true);
insert into cubicle(cubicle_number,isVacant) values("2F008",true);
insert into cubicle(cubicle_number,isVacant) values("2F009",true);
insert into cubicle(cubicle_number,isVacant) values("2F010",true);

insert into cubicle(cubicle_number,floor_id,isVacant,allocated_to) values("4F001",5,false,5);
insert into cubicle(cubicle_number,floor_id,isVacant,allocated_to) values("4F002",11,false,11);
insert into cubicle(cubicle_number,floor_id,isVacant,allocated_to) values("4F003",17,false,17);
insert into cubicle(cubicle_number,isVacant) values("2F004",true);
insert into cubicle(cubicle_number,isVacant) values("2F005",true);
insert into cubicle(cubicle_number,isVacant) values("2F006",true);
insert into cubicle(cubicle_number,isVacant) values("2F007",true);
insert into cubicle(cubicle_number,isVacant) values("2F008",true);
insert into cubicle(cubicle_number,isVacant) values("2F009",true);
insert into cubicle(cubicle_number,isVacant) values("2F010",true);

select * from cubicle;
select * from employee;
select * from floors;
select * from department;

drop table cubicle;
drop table employee;
drop table floors;
drop table department;
